name: "Docs automation"
description: "Автоматизирует формирование документов по частям."
icon: "book"
color: "yellow"
inputs:
  message:
    description: "Message to print"
    required: true
    default: "Hello, World!"
outputs:
  result:
    description: "The result of the Action"
runs:
  using: "composite"
  steps:
    - name: Print message
      run: echo "${{ inputs.message }}"
    - name: Set output
      run: echo "result=Done" >> $GITHUB_ENV
